version: '3.8'

services:
  rhel8:
    image: registry.access.redhat.com/ubi8/ubi:latest
    container_name: rhel8
    command: /sbin/init
    privileged: true
    networks:
      - stagiaires_net

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: stagiaire
      MYSQL_PASSWORD: motdepasse
      MYSQL_DATABASE: stagiaire_db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - stagiaires_net
    ports:
      - "3306:3306"

volumes:
  mariadb_data:

networks:
  stagiaires_net:
    driver: bridge
